

all: 
	 tcc xdemo-keypress.c  -o xdemo-keypress -lX11
	 tcc xdemo-paint.c  -o xdemo-paint -lX11 
	 tcc xdemo-mouse.c  -o xdemo-mouse -lX11 


run: 
	 tcc xdemo-mouse.c  -o xdemo-mouse -lX11 ; ./xdemo-mouse 
